# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0e23a4d534c81382c6b9f19b3a48940d4d3f4cacdebef2f3cd8d02df1feb316c4e111d482b6def0d36e17bfebb9f79977eac765ddf3738b25e0919ed4c4eea

test:
  secret_key_base: 9158347dc578f12585d679984c25930f4ad006c2fc8893dd6923122ebebca7fb56c39a5256c6867b252f0b492636dded59493d0bc2c63190d67139b7dd295659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
